from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, EmailStr
import uuid

#-------- User Base --------------
class UserBase(BaseModel):
    username: str = Field(min_length=1, max_length=50)
    email: EmailStr = Field(max_length=120)


class UserCreate(UserBase):
    password: str = Field(min_length=8)

class UserResponse(UserBase):
    model_config = ConfigDict(from_attributes=True)
   



#-------- POST Schema ----------

# 1. Base Schema: Contains fields shared by both Request and Response
class PostBase(BaseModel):
    title: str = Field(min_length=10, max_length=100, description="The title of the blog post")
    content: str = Field(min_length=65, description="The main body text of the blog post (must be at least 65 characters)")
    author: str = Field(min_length=2, max_length=50, description="The name of the author")
    image_url: str | None = None
    video_url: str | None = None
    reference_url: str | None = None


# 2. Request Schema: Used for validating incoming POST/PUT request bodies
# It inherits everything from PostBase. No extra fields are needed for creation.
class PostCreate(PostBase):
    user_id: uuid.UUID

class PostUpdate(BaseModel):
    title: str | None = Field(None, min_length=10, max_length=100)
    content: str | None = Field(None, min_length=65)
    image_url: str | None = None
    video_url: str | None = None
    reference_url: str | None = None


# 3. Response Schema: Used for validating and filtering outgoing API responses
# It inherits all fields from PostBase, but also includes fields generated by the backend/DB.
class PostResponse(PostBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    user_id: int
    date_posted: datetime
    likes: int
 
class UploadURLRequest(BaseModel):
    content_type:str 

class UploadURLResponse(BaseModel):
    upload_url:str
    fields:dict
    file_url:str
